version: '3.4'    
services:
      api:
        container_name: api
        build:
          context: ./
          dockerfile: ./Bug.API/Dockerfile
        ports:
          - "44:4444"
        depends_on:
          - "nginx"
          - "sqldata"
        restart: always
      client:
        container_name: client
        build:
          context: ./Bug.Client
          dockerfile: ./Dockerfile
        ports:
          - "55:5555"
          
        depends_on:
          - "nginx"
        restart: always
      sqldata:
        container_name: sql
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Pass@word"
          MSSQL_PID: Developer
        ports:
          - "33:3333"
      nginx:
        container_name: nginx
        build: 
            context: ./Nginx
            dockerfile: Dockerfile
        ports: 
            - 80:80
            - 443:443
        restart: always
          