version: '3.4'    
services:
      api:
        container_name: api
        build:
          context: ./
          dockerfile: ./Bug.API/Dockerfile
        ports: 
          - "4444:80"
        depends_on:
          - "nginx"
          - "sqldata"
      client:
        container_name: client
        build:
          context: ./Bug.Client
          dockerfile: ./Dockerfile
        ports:
          - "5555:80"
        depends_on:
          - "nginx"
      sqldata:
        container_name: sql
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Pass@word"
          MSSQL_PID: Developer
        ports:
          - "3333:80"
      nginx:
        container_name: nginx
        build: 
            context: ./Nginx
            dockerfile: Dockerfile
        ports: 
            - 80:80
        restart: always
          